server:
  port: 8080
  shutdown: immediate

spring:
  application:
    name: orders-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
    consumer:
      group-id: orders-ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.joaocarlos.core.*"
    listener:
      observation-enabled: true
    template:
      observation-enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

orders:
  events:
    topic:
      name: orders-events
  outbox:
    retention-days: 7
    publisher:
      fixed-delay-ms: 5000
      batch-size: 50
      max-retries: 3
    cleaner:
      cron: "0 0 3 * * *"


order:
  commands:
    topic:
      name: order-commands

management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.joaocarlos: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: DEBUG
    org.springframework.boot.docker.compose: DEBUG